Vagrant::Config.run do |config|
    config.vm.box = "precise32"
    config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.host_name = "wowf.localdomain"
    config.vm.network :hostonly, "10.10.10.10"
    config.vm.forward_port 80, 8080
    config.vm.provision :shell, :inline => "apt-get update --fix-broken --fix-missing"
    config.vm.provision :shell, :path => "blueprint.sh"
end